// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class CardPurchase {
  static encode(message: CardPurchase, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.txHash);

    writer.uint32(16);
    writer.uint64(message.cardId);

    writer.uint32(26);
    writer.string(message.buyer);

    writer.uint32(34);
    writer.string(message.buyerVault);

    writer.uint32(40);
    writer.uint64(message.amount);

    writer.uint32(50);
    writer.string(message.cardType);

    writer.uint32(56);
    writer.int64(message.timestamp);

    writer.uint32(64);
    writer.uint64(message.slot);

    writer.uint32(72);
    writer.uint64(message.blockHeight);

    writer.uint32(82);
    writer.string(message.blockhash);
  }

  static decode(reader: Reader, length: i32): CardPurchase {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CardPurchase();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.txHash = reader.string();
          break;

        case 2:
          message.cardId = reader.uint64();
          break;

        case 3:
          message.buyer = reader.string();
          break;

        case 4:
          message.buyerVault = reader.string();
          break;

        case 5:
          message.amount = reader.uint64();
          break;

        case 6:
          message.cardType = reader.string();
          break;

        case 7:
          message.timestamp = reader.int64();
          break;

        case 8:
          message.slot = reader.uint64();
          break;

        case 9:
          message.blockHeight = reader.uint64();
          break;

        case 10:
          message.blockhash = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  txHash: string;
  cardId: u64;
  buyer: string;
  buyerVault: string;
  amount: u64;
  cardType: string;
  timestamp: i64;
  slot: u64;
  blockHeight: u64;
  blockhash: string;

  constructor(
    txHash: string = "",
    cardId: u64 = 0,
    buyer: string = "",
    buyerVault: string = "",
    amount: u64 = 0,
    cardType: string = "",
    timestamp: i64 = 0,
    slot: u64 = 0,
    blockHeight: u64 = 0,
    blockhash: string = ""
  ) {
    this.txHash = txHash;
    this.cardId = cardId;
    this.buyer = buyer;
    this.buyerVault = buyerVault;
    this.amount = amount;
    this.cardType = cardType;
    this.timestamp = timestamp;
    this.slot = slot;
    this.blockHeight = blockHeight;
    this.blockhash = blockhash;
  }
}
