// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class CardBotDirectCardPurchase {
  static encode(message: CardBotDirectCardPurchase, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.slot);

    writer.uint32(16);
    writer.uint64(message.blockHeight);

    writer.uint32(26);
    writer.string(message.blockhash);

    writer.uint32(32);
    writer.int64(message.timestamp);

    writer.uint32(42);
    writer.string(message.txHash);

    writer.uint32(50);
    writer.string(message.userId);

    writer.uint32(58);
    writer.string(message.inputToken);

    writer.uint32(66);
    writer.string(message.outputToken);

    writer.uint32(72);
    writer.uint64(message.inputAmount);

    writer.uint32(80);
    writer.uint64(message.outputAmount);

    writer.uint32(90);
    writer.string(message.userCustody);

    writer.uint32(98);
    writer.string(message.admin);
  }

  static decode(reader: Reader, length: i32): CardBotDirectCardPurchase {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CardBotDirectCardPurchase();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.slot = reader.uint64();
          break;

        case 2:
          message.blockHeight = reader.uint64();
          break;

        case 3:
          message.blockhash = reader.string();
          break;

        case 4:
          message.timestamp = reader.int64();
          break;

        case 5:
          message.txHash = reader.string();
          break;

        case 6:
          message.userId = reader.string();
          break;

        case 7:
          message.inputToken = reader.string();
          break;

        case 8:
          message.outputToken = reader.string();
          break;

        case 9:
          message.inputAmount = reader.uint64();
          break;

        case 10:
          message.outputAmount = reader.uint64();
          break;

        case 11:
          message.userCustody = reader.string();
          break;

        case 12:
          message.admin = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  slot: u64;
  blockHeight: u64;
  blockhash: string;
  timestamp: i64;
  txHash: string;
  userId: string;
  inputToken: string;
  outputToken: string;
  inputAmount: u64;
  outputAmount: u64;
  userCustody: string;
  admin: string;

  constructor(
    slot: u64 = 0,
    blockHeight: u64 = 0,
    blockhash: string = "",
    timestamp: i64 = 0,
    txHash: string = "",
    userId: string = "",
    inputToken: string = "",
    outputToken: string = "",
    inputAmount: u64 = 0,
    outputAmount: u64 = 0,
    userCustody: string = "",
    admin: string = ""
  ) {
    this.slot = slot;
    this.blockHeight = blockHeight;
    this.blockhash = blockhash;
    this.timestamp = timestamp;
    this.txHash = txHash;
    this.userId = userId;
    this.inputToken = inputToken;
    this.outputToken = outputToken;
    this.inputAmount = inputAmount;
    this.outputAmount = outputAmount;
    this.userCustody = userCustody;
    this.admin = admin;
  }
}
