// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { DepositType } from "./DepositType";

export class Deposit {
  static encode(message: Deposit, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.slot);

    writer.uint32(16);
    writer.uint64(message.blockHeight);

    writer.uint32(26);
    writer.string(message.blockhash);

    writer.uint32(32);
    writer.int64(message.timestamp);

    writer.uint32(42);
    writer.string(message.txHash);

    writer.uint32(48);
    writer.uint64(message.inputAmount);

    writer.uint32(56);
    writer.uint64(message.outputAmount);

    writer.uint32(66);
    writer.string(message.inputToken);

    writer.uint32(74);
    writer.string(message.outputToken);

    writer.uint32(80);
    writer.int32(message.depositType);

    writer.uint32(90);
    writer.string(message.depositor);

    writer.uint32(98);
    writer.string(message.userVault);

    writer.uint32(106);
    writer.string(message.purchaseRecord);
  }

  static decode(reader: Reader, length: i32): Deposit {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Deposit();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.slot = reader.uint64();
          break;

        case 2:
          message.blockHeight = reader.uint64();
          break;

        case 3:
          message.blockhash = reader.string();
          break;

        case 4:
          message.timestamp = reader.int64();
          break;

        case 5:
          message.txHash = reader.string();
          break;

        case 6:
          message.inputAmount = reader.uint64();
          break;

        case 7:
          message.outputAmount = reader.uint64();
          break;

        case 8:
          message.inputToken = reader.string();
          break;

        case 9:
          message.outputToken = reader.string();
          break;

        case 10:
          message.depositType = reader.int32();
          break;

        case 11:
          message.depositor = reader.string();
          break;

        case 12:
          message.userVault = reader.string();
          break;

        case 13:
          message.purchaseRecord = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  slot: u64;
  blockHeight: u64;
  blockhash: string;
  timestamp: i64;
  txHash: string;
  inputAmount: u64;
  outputAmount: u64;
  inputToken: string;
  outputToken: string;
  depositType: DepositType;
  depositor: string;
  userVault: string;
  purchaseRecord: string;

  constructor(
    slot: u64 = 0,
    blockHeight: u64 = 0,
    blockhash: string = "",
    timestamp: i64 = 0,
    txHash: string = "",
    inputAmount: u64 = 0,
    outputAmount: u64 = 0,
    inputToken: string = "",
    outputToken: string = "",
    depositType: DepositType = 0,
    depositor: string = "",
    userVault: string = "",
    purchaseRecord: string = ""
  ) {
    this.slot = slot;
    this.blockHeight = blockHeight;
    this.blockhash = blockhash;
    this.timestamp = timestamp;
    this.txHash = txHash;
    this.inputAmount = inputAmount;
    this.outputAmount = outputAmount;
    this.inputToken = inputToken;
    this.outputToken = outputToken;
    this.depositType = depositType;
    this.depositor = depositor;
    this.userVault = userVault;
    this.purchaseRecord = purchaseRecord;
  }
}
