// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

export enum DepositType {
  DEPOSIT_TYPE_UNSPECIFIED = 0,
  DEPOSIT_TYPE_USDC = 1,
  DEPOSIT_TYPE_NATIVE = 2,
  DEPOSIT_TYPE_NON_NATIVE = 3,
}
