// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Deposit } from "./Deposit";

export class Output {
  static encode(message: Output, writer: Writer): void {
    const deposits = message.deposits;
    for (let i: i32 = 0; i < deposits.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Deposit.encode(deposits[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Output {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Output();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.deposits.push(Deposit.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  deposits: Array<Deposit>;

  constructor(deposits: Array<Deposit> = []) {
    this.deposits = deposits;
  }
}
